Release version 1.8.0
please-build/puku pull request #116
Opened 2024-07-09 13:39 UTC by SpangleLabs

This updates the changelog with #114 and bumps the version to 1.8.0, as this is a minor functional change

I'm not sure if the changelog should also contain #111 and #113, which were both landed since the last release?

2024-07-09 14:04 UTC, goddenrich approved these changes

2024-07-09 14:07 UTC, goddenrich commented
> This updates the changelog with #114 and bumps the version to 1.8.0, as this is a minor functional change
> 
> I'm not sure if the changelog should also contain #111 and #113, which were both landed since the last release?

#111 is not a functional change it is just a refactor so doesn't need included. #113 should be added

2024-07-09 14:08 UTC, goddenrich requested changes

2024-07-09 14:08 UTC, goddenrich commented on ChangeLog
> +    * Puku sync will now add `go_replace_directive` labels to any go_repo targets with a replace directive in the go.mod file (#114)
#113 is missing

2024-07-09 15:46 UTC, SpangleLabs commented on ChangeLog
> +    * Puku sync will now add `go_replace_directive` labels to any go_repo targets with a replace directive in the go.mod file (#114)
Added that now

2024-07-09 15:47 UTC, SpangleLabs commented
Okay, I've added reference to #113 in the changelog now

2024-07-11 14:23 UTC, goddenrich approved these changes

2024-07-11 14:23 UTC, merged